import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/_partial/Header";
import Footer from "@/components/ui/_partial/Footer";
import {UserProvider} from "@/context/UserContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Header />
            <div className="min-h-screen bg-slate-700 text-white pt-[450px]">
              {children}           
            </div>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
